name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          # SSH into the server and deploy updates
          ssh -o StrictHostKeyChecking=no user@your-server-ip <<EOF
            cd /
            git pull origin main
            systemctl restart fastapi-app.service
          EOF
